/**:
  ros__parameters:
    camera:
      i_enable_imu: true
      i_enable_ir: true
      i_nn_type: none
      i_pipeline_type: RGBD
    stereo:
      i_align_depth: true # Required to map depth to RGB
      i_publish_topic: true