/oak:
  ros__parameters:
    pointcloud:
      i_enable: false
    camera:
      i_enable_imu: true
      i_enable_ir: true
      i_nn_type: none
      i_pipeline_type: depth
    stereo:
      i_align_depth: true
      i_board_socket_id: 2
      i_subpixel: true
      i_right_rect_publish_topic: true
      i_right_rect_synced: false
      i_publish_topic: false
      i_enable_decimation_filter: true
      i_decimation_filter_decimation_factor: 4
      i_lr_check: true
