/oak:
  ros__parameters:
    camera:
      i_enable_imu: true
      i_enable_ir: true
      i_nn_type: none
      i_pipeline_type: depth
    rgb:
      i_width: 640
      i_height: 360
      i_fps: 20.0
    stereo:
      i_align_depth: true
      i_subpixel: true
      i_lr_check: true
      i_width: 640
      i_height: 400
      i_fps: 20.0
      i_enable_decimation_filter: true
      i_decimation_filter_decimation_factor: 2
