cam_ops_node:
  ros__parameters:
    image_topic: /oak/rgb/image_raw
    depth_topic: /oak/stereo/image_raw
    camera_info_topic: /oak/rgb/camera_info
    target_topic: /user_pos
    target_valid_topic: /user_valid
    debug_image_topic: /robot/debug/cam_ops_image
    min_pink_area_px: 300
    enable_resize: true
    resize_scale: 0.5
    min_depth_m: 0.2
    max_depth_m: 8.0
    depth_window_radius_px: 2
yolo26_node:
  ros__parameters:
    image_topic: /oak/rgb/image_raw
    depth_topic: /oak/stereo/image_raw
    camera_info_topic: /oak/rgb/camera_info
    model_path: /home/box/TeamBowl/models/yolo26s.engine
    min_confidence: 0.5
    min_depth_m: 0.2
    max_depth_m: 8.0
    depth_window_radius_px: 2
    target_lost_timeout_s: 3600.0
    tracker_config: /workspaces/teambowl_ws/src/perception/config/botsort.yaml
