cmd_vel_to_vesc:
  ros__parameters:
    cmd_vel_topic: /cmd_vel
    left_port: /dev/ttyACM0
    right_port: /dev/ttyACM1
    estop_topic: /estop
    wheel_radius_m: 0.157485
    track_width_m: 0.568643
    erpm_per_wheel_rpm: 101.5
    max_erpm_step_per_tick: 200
    max_erpm: 2560
    cmd_timeout_s: 0.5
    baud: 115200
    serial_timeout_s: 0.05
    left_sign: -1
    right_sign: -1
    print_RPM_cmds: false
    left_wheel_vel_topic: /wheel_vel_left
    right_wheel_vel_topic: /wheel_vel_right
    feedback_poll_rate_hz: 20.0
    publish_wheel_feedback: true
